services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mydb
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb
      MYSQL_PASSWORD: mydb
    volumes:
      - ./dbData:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
      PMA_USER: mydb
      PMA_PASSWORD: mydb
      MEMORY_LIMIT: 1G
      UPLOAD_LIMIT: 512M
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
